# {NAME} = Nom du joueur
# {PREFIX} = Prefix du rank du joueur
# {RANK} = Rank du joueur
# {FAC_NAME} = Faction du joueur
# {FAC_RANK} = Grade du joueur dans sa faction

#Json, Yaml, SQLite3, MySQL
database-provider: Json
lang: "fra"

mysql:
  host: "localhost"
  username: "root"
  password: "Password"
  database: "rank"

faction-system: true
annonce-rank: "§7[§c!§7] {NAME} §6a obtenu le grade §7{PREFIX}" #paste to fra.ini
basic-rank: "Player"

no-faction: "..."

#ne marche pas si le plugins a deja un systeme de role
leader-faction-rank: "**"
officer-faction-rank: "*"
no-faction-rank: ""

gametag-prefix-default: "§7{NAME} - {FAC_NAME} [{PREFIX}§r§7]"
chat-prefix-default: "§f[§7{FAC_NAME}§e{FAC_RANK}§f]§7 {PREFIX}§r§7 {NAME} §f> §7{MSG}"

